yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'posts'

urlpatterns = [
    path('', views.index, name='main'),
    path('group/<slug:slug>/', views.group_posts, name='group_posts'),
    # Профайл пользователя
    path('profile/<str:username>/', views.profile, name='profile'),
    # Просмотр записи
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    # Новая страница
    path('create/', views.post_create, name='post_create'),
    # редактирование записи
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.db.models import UniqueConstraint

User = get_user_model()

NUM_SYMBOLS = 15


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=300, unique=True)
    description = models.TextField(max_length=400)

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        'Текст поста',
        help_text='Введите текст поста'
    )
    pub_date = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='posts',
        verbose_name='Группа',
        help_text='Выберите группу'
    )
    # Поле для картинки (необязательное)
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.text[:NUM_SYMBOLS]


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE,
                             related_name='comments')
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name='comments')

    text = models.TextField(
        help_text='Здесь следует ввести текст комментария'
    )

    created = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)

    class Meta:
        ordering = ['created']


class Follow(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               verbose_name='Подписка',
                               related_name='following',
                               help_text='Подписан на')
    user = models.ForeignKey(User, on_delete=models.CASCADE,
                             verbose_name='Подписчик',
                             related_name='follower',
                             help_text='Подписчик',
                             null=True)

    class Meta:
        UniqueConstraint(fields=['author', 'user'], name='follow_unique')

yatube/posts/forms.py
from django import forms
from posts.models import Post, Comment


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['text', 'group', 'image']
        labels = {
            'text': 'Текст поста',
            'group': 'Группа',
            'image': 'Картинка'
        }
        help_texts = {
            'text': 'Текст нового поста',
            'group': 'Группа, к которой будет относиться пост',
            'image': 'Картинка нового поста'
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

yatube/posts/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Group, Follow
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from posts.forms import PostForm, CommentForm
from django.views.decorators.cache import cache_page

NUMBER_POSTS = 10
CACHE_SECOND = 20


@cache_page(CACHE_SECOND)
def index(request):
    title = 'Последние обновления на сайте'
    post_list = Post.objects.select_related('group').all()
    paginator = Paginator(post_list, NUMBER_POSTS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'title': title,
    }

    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.all()
    paginator = Paginator(post_list, NUMBER_POSTS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    title = username + ' профайл пользователя'
    author = get_object_or_404(User, username=username)
    posts = author.posts.all()
    paginator = Paginator(posts, NUMBER_POSTS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    post_number = posts.count()
    following = request.user.is_authenticated and Follow.objects.filter(
        user=request.user, author=author).exists()
    context = {
        'post_number': post_number,
        'page_obj': page_obj,
        'author': author,
        'title': title,
        'following': following,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    form = CommentForm(request.POST or None)
    post = get_object_or_404(Post, id=post_id)
    get_user_object = User.objects.get(id=post.author_id)
    user = get_user_object.username
    post_list = Post.objects.filter(author=get_user_object)
    posts_count = post_list.count()
    comments = post.comments.all()
    context = {
        'username': user,
        'post': post,
        'posts_count': posts_count,
        'form': form,
        'post_view': True,
        'comment': comments,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    template_name = 'posts/create_post.html'
    form = PostForm(
        request.POST or None,
        files=request.FILES or None
    )
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        username = post.author.username
        return redirect('posts:profile', username)
    return render(request, template_name, {'form': form})


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id=post_id)

    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post_id)
    context = {
        'post': post,
        'form': form,
        'is_edit': True,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    """Информация о текущем пользователе доступна в переменной request.user."""
    follow_posts = Post.objects.filter(author__following__user=request.user)
    paginator = Paginator(follow_posts, NUMBER_POSTS)
    page_number = request.GET.get('page_obj')
    page_obj = paginator.get_page(page_number)
    context = {
        'paginator': paginator,
        'page_obj': page_obj,
    }
    return render(request, "posts/follow.html", context)


@login_required
def profile_follow(request, username):
    """Подписаться на автора."""
    author = get_object_or_404(User, username=username)
    user = request.user
    if (
        author != request.user and not
        Follow.objects.filter(author=author, user=user).exists()
    ):
        Follow.objects.create(user=user, author=author)
    return redirect('posts:profile', username)


@login_required
def profile_unfollow(request, username):
    """Дизлайк, отписка."""
    author = get_object_or_404(User, username=username)
    Follow.objects.filter(user=request.user, author=author).delete()
    return redirect('posts:profile', username=author.username)

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% block title %}
{% if not post %}Добавить запись {% else %} Редактировать запись {% endif %}
{% endblock %}
{% block content %}
{% load user_filters %}
{% load thumbnail %}

<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          {% if not post %} Новый пост {% else %} Редактировать запись {% endif %}
        </div>
            <div class="card-body">

                {% for error in form.errors %}
                        <div class="alert alert-danger" role="alert">
                          {{ error|escape }}
                        </div>
                    {% endfor %}

                    <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                  
                   
                    {% for field in form %}
                    <div class="form-group row my-3"
                    aria-required={% if field.field.required %}"true"
                    {% else %}
                    "false"
                    {% endif %}>
                            <label for="{{ field.id_for_label }}"
 
                            class="col-md-4 col-form-label text-md-right">{{ field.label }}
                              {% if field.field.required %}
                              <span class="required text-danger">*</span>
                              {% endif %}
                            </label>
                            <small id="id_text-help" class="form-text text-muted">
                            <div class="form-group row my-3 p-3">

                                {# подключаем фильтр и указываем класс #}
                                {{ field|addclass:"form-control" }}
                                
                                {% if field.help_text %}
                                <small id="{{ field.id_for_label }}-help"
                                class="form-text text-muted">
                                {{ field.help_text|safe }}</small>
                                {% endif %}
                            </div>
                    </div>
                {% endfor %}
                <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                        {% if post %} Сохранить
                        {% else %} Добавить
                        {% endif %}
                    </button>
                </div>
            </div> <!-- card body -->
        </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->
{% endblock %}

yatube/templates/posts/follow.html
{% extends "base.html" %}
{% block title %}Посты авторов, на которых вы подписаны{% endblock %}
{% block header %}Посты авторов, на которых вы подписаны{% endblock %}
{% block content %}

{% include 'includes/switcher.html' %}
  {% for post in page_obj %}
  {% include 'includes/show_post.html' %}
  {% if post.group.title != None %}
    <a href="{% url 'posts:group_posts' post.group.slug %}">все записи группы</a>
  {% endif %}
  {% endfor %}

  {% include 'posts/includes/paginator.html' %}

{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %} Записи сообщества {{ group }}{% endblock %}
{% block content %}
      <!-- класс py-5 создает отступы сверху и снизу блока -->
      <div class="container py-5">
        <h1>{% block header %}{{ group }}{% endblock %}</h1>
        <p>{{ group.description }}</p>
        <article>
          {% for post in page_obj %}
            {% include 'includes/show_post.html' %}
          {% endfor %}
        </article>

      </div>

{% include 'posts/includes/paginator.html' %}
{% endblock content %}

yatube/templates/posts/index.html
{% extends "base.html" %}
{% block title %}{{title}}{% endblock %}
{% block header %}{{title}}{% endblock %}
{% block content %}

{% include 'includes/switcher.html' %}
  {% for post in page_obj %}
  {% include 'includes/show_post.html' %}
  {% if post.group.title != None %}
    <a href="{% url 'posts:group_posts' post.group.slug %}">все записи группы</a>
  {% endif %}
  {% endfor %}

  {% include 'posts/includes/paginator.html' %}

{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}

{% block title %}
         Пост {{  post.text|truncatechars:30 }}
{% endblock %}

{% block content %}
{% load thumbnail %}

    <div class="container py-5">
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
            {% if post.group != NULL %}
              <li class="list-group-item">
                Группа: <span >{{ post.group }}</span>
                <a href="{% url 'posts:group_posts' post.group.slug %}">
                  все записи группы </a>
              </li>

            {% endif %}
            <li class="list-group-item">
              Автор: {{ post.author.get_full_name }}
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
            Всего постов автора:  <span >{{ posts_count}}</span>
          </li>
            <li class="list-group-item">
              <a href="{% url 'posts:profile' post.author.username %}">
                все посты пользователя {{ post.author.get_full_name }}
              </a>
            </li>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          {% thumbnail post.image "960x339" padding=True upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p>
            {{ post.text }}
          </p>
          {% if request.user == post.author %}
          <a class="btn btn-primary" href="{% url 'posts:post_edit' post.pk %}">
            редактировать запись
          </a>
          {% endif %}

          {% include 'includes/comments.html' %}

        </article>
      </div>
    </div>

     {% endblock %}

yatube/templates/posts/post_edit.html
{% extends 'base.html' %}
{% block title %}Редактировать пост{% endblock %}
{% block content %}

      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Редактировать пост
              </div>
              <div class="card-body">
                <form method="post" action="../posts/create_post.html">
                  <input type="hidden" name="csrfmiddlewaretoken" value="">
                  <div class="form-group row my-3 p-3">
                    <label for="id_text">
                      Текст поста
                      <span class="required text-danger" >*</span>
                    </label>
                    <textarea name="text" cols="40" rows="10" class="form-control" required id="id_text">[Фокшаны.] Еще переходъ до Фокшанъ, во время котораго я ѣхалъ съ Монго. Человѣкъ пустой, но съ твердыми, хотя и ложными убѣжденіями. Генерал[у] по этому должно быть случаю, угодно было спрашивать о моемъ здоровьи. Свинья! К[о]вырялъ носъ и ничего не написалъ — вотъ 2 упрека за нын[ѣшній] день. Послѣдній упрекъ становится слишкомъ частъ, хотя походъ и можетъ служить въ немъ отчасти извиненіемъ. Отношенія мои съ товарищами становятся такъ пріятны, что мнѣ жалко бросить штабъ. Здоровье кажется (2) лучше.
                    </textarea>
                    <small id="id_text-help" class="form-text text-muted">
                      Текст нового поста
                    </small>
                  </div>
                  <div class="form-group row my-3 p-3">
                    <label for="id_group">
                      Group
                    </label>
                    <select name="group" class="form-control" id="id_group">
                      <option value="">---------</option>
                      <option value="1" selected>Группа: Лев Толстой – зеркало русской революции</option>
                    </select>
                    <small id="id_group-help" class="form-text text-muted">
                      Группа, к которой будет относиться пост
                    </small>
                  </div>
                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                      Добавить
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}

{% block title %}
    {{ title}}
{% endblock %}

{% block content %}
{% load thumbnail %}
  <div class="container py-5">
    <div class="mb-5">
    <h1>Все посты пользователя {{ author.get_full_name }} </h1>
    <h3>Всего постов: {{ post_number }} </h3>

  {% if user != author and user.is_authenticated %}

    {% if following %}
    <a
      class="btn btn-lg btn-light"
      href="{% url 'posts:profile_unfollow' author.username %}" role="button"
    >
      Отписаться
    </a>
  {% else %}
      <a
        class="btn btn-lg btn-primary"
        href="{% url 'posts:profile_follow' author.username %}" role="button"
      >
        Подписаться
      </a>
      {% endif %}

  {% endif %}

    </div>
        {% for post in page_obj %}
        <article>
          <ul>
            <li>
              Автор: {{ post.author.get_full_name }}
            </li>
            <li>
                Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
          </ul>
          {% thumbnail post.image "960x339" padding=True upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
          <p>
            {{ post.text }}
          </p>
          <a href="{% url 'posts:post_detail' post.id %}">подробная информация </a>

        </article>
        {% if post.group_id != NULL %}
        <a href="{% url 'posts:group_posts' post.group.slug %}">все записи группы</a>
        {% endif %}
      {% if not forloop.last %}<hr>{% endif %}

      {% endfor %}
      {% include 'posts/includes/paginator.html' %}
    </div>
      {% endblock %}